---
- hosts: localhost
  tasks:
    - name: "Env vars"
      shell: "echo KERNEL=kernel_2712"

    - name: "Make config"
      make:
        chdir: ../../
        target: bcm2712_defconfig
        params:
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-

    - name: "Compile RPI Kernel"
      make:
        chdir: ../../
        target: Image modules dtbs
        params:
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-
          NUM_THREADS: 16
