---
- hosts: localhost
  tasks:
    - name: "Env vars"
      shell: "echo KERNEL=kernel_2712"

    - name: "Make config"
      make:
        chdir: ../../
        target: bcm2712_defconfig
        params:
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-

    - name: "Compile RPI Kernel [Image]"
      make:
        chdir: ../../
        target: Image
        jobs: 16
        params:
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-

    - name: "Compile RPI Kernel [modules]"
      make:
        chdir: ../../
        target: modules
        jobs: 16
        params:
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-
          j: 6

    - name: "Compile RPI Kernel [dtbs]"
      make:
        chdir: ../../
        target: dtbs
        jobs: 16
        params:
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-
          j: 6

- hosts: nazgul-ii
  tasks:
    - name: "Copy src to remote"
      copy:
        src: "../../../linux/"
        dest: /home/judgeglass/test
        owner: judgeglass
